version: '3.1'
services:
  influxdb:
    image: influxdb
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: influx
      INFLUXDB_USER: influx
      INFLUXDB_USER_PASSWORD: influx
      INFLUXDB_GRAPHITE_ENABLED: 'true'
    expose:
      - 8086
    ports:
      - 8086:8086
      - 2003:2003

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

volumes:
  influx-data: