version: '3.1'
services:
  influxdb:
    image: influxdb
    restart: always
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: db0
#      INFLUXDB_USER: uinflux
#      INFLUXDB_USER_PASSWORD: pinflux
#      INFLUXDB_GRAPHITE_ENABLED: 'true'
    expose:
      - 8086
      - 2003
    ports:
      - 8086:8086
      - 2003:2003

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
