version: '3.8'
services:
  harbor-nginx:
    image: nginx:alpine
    volumes:
    - ./templates:/etc/nginx/templates
    - ./html:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./vision-local-cert.key:/etc/nginx/vision-local-cert.key
    - ./vision-local-cert.pem:/etc/nginx/vision-local-cert.pem
    ports:
      - 8080:8080
      - 8443:8443
